// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvifnQ0MiIsfEfRv2tW14dYe75xDZde8g',
    appId: '1:202402979155:web:411593f38ee6425d9a55a6',
    messagingSenderId: '202402979155',
    projectId: 'mynotes-flutter-pp',
    authDomain: 'mynotes-flutter-pp.firebaseapp.com',
    storageBucket: 'mynotes-flutter-pp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHq8TILLIusZF3vi54vBiPHVtAYqzxJc',
    appId: '1:202402979155:android:b12846c51de3943c9a55a6',
    messagingSenderId: '202402979155',
    projectId: 'mynotes-flutter-pp',
    storageBucket: 'mynotes-flutter-pp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lk9CVqgXC6IsmpzVfIigisHfuBilGbk',
    appId: '1:202402979155:ios:68619076ae9fb4119a55a6',
    messagingSenderId: '202402979155',
    projectId: 'mynotes-flutter-pp',
    storageBucket: 'mynotes-flutter-pp.appspot.com',
    iosBundleId: 'com.vivek-sharma.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6lk9CVqgXC6IsmpzVfIigisHfuBilGbk',
    appId: '1:202402979155:ios:aba0fc2552de4f0f9a55a6',
    messagingSenderId: '202402979155',
    projectId: 'mynotes-flutter-pp',
    storageBucket: 'mynotes-flutter-pp.appspot.com',
    iosBundleId: 'com.vivek-sharma.mynotes.RunnerTests',
  );
}
